# Generated by Django 2.1.2 on 2019-01-02 16:42

from django.db import migrations, models
import django.db.models.deletion
import localized_fields.fields.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('additional_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_singular', localized_fields.fields.field.LocalizedField(required=['en'], uniqueness=[], verbose_name='name singular')),
                ('name_plural', localized_fields.fields.field.LocalizedField(required=['en'], uniqueness=[], verbose_name='name plural')),
                ('name_latin', models.TextField(null=True, verbose_name='name latin')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='farming.CropSpecies')),
            ],
            options={
                'verbose_name_plural': 'crop species',
                'ordering': ('name_singular',),
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('additional_services', models.ManyToManyField(blank=True, related_name='farms', to='additional_services.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to='core.FaSTUser')),
            ],
        ),
        migrations.CreateModel(
            name='FarmingCommitment',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', localized_fields.fields.field.LocalizedField(required=['en'], uniqueness=[], verbose_name='name')),
                ('available_countries', models.ManyToManyField(to='core.Country')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FarmLivestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_heads', models.IntegerField()),
                ('start_at', models.DateField(blank=True, null=True)),
                ('end_at', models.DateField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_livestock', to='farming.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmParcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('lpis_parcel_id', models.CharField(max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_parcels_added', to='core.FaSTUser')),
                ('crop_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_parcels', to='farming.CropSpecies')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_parcels', to='farming.Farm')),
                ('farming_commitments', models.ManyToManyField(blank=True, related_name='farm_parcels', to='farming.FarmingCommitment')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='farming/livestock_species/icons/%Y/%m/%d/', verbose_name='icon')),
                ('name_singular', localized_fields.fields.field.LocalizedField(required=['en'], uniqueness=[], verbose_name='name singular')),
                ('name_plural', localized_fields.fields.field.LocalizedField(required=['en'], uniqueness=[], verbose_name='name plural')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='farming.LivestockSpecies', verbose_name='parent')),
            ],
            options={
                'verbose_name_plural': 'livestock species',
                'ordering': ('name_singular',),
            },
        ),
        migrations.AddField(
            model_name='farmlivestock',
            name='livestock_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farm_livestock_species', to='farming.LivestockSpecies'),
        ),
        migrations.AddField(
            model_name='farm',
            name='farmers',
            field=models.ManyToManyField(blank=True, related_name='farms', to='farming.Farmer'),
        ),
    ]
