# Generated by Django 2.1.2 on 2019-01-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='additional_services',
        ),
    ]
