# Generated by Django 2.1.2 on 2019-01-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0002_remove_farm_additional_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropspecies',
            name='default_yield_per_hectare',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
