# Generated by Django 2.1.5 on 2019-01-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0003_cropspecies_default_yield_per_hectare'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockspecies',
            name='default_manure_liters_per_head_per_day',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestockspecies',
            name='default_manure_nitrogen_content',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestockspecies',
            name='default_manure_phosphorus_content',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestockspecies',
            name='default_manure_potassium_content',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestockspecies',
            name='default_manure_purity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestockspecies',
            name='default_manure_storage_days',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
