fragment fragmentMessagingNewMessagesInThreadFeedItem on MessagingNewMessagesInThreadFeedItemType {
  id
  __typename
  timestamp
  timegroup
  component
  thread {
    id
    subject
    messages {
      id
      createdBy {
        id
        fullName
      }
    }
  }
  numberOfNewMessages
}
