#import "./fragmentPlan.gql"

mutation updatePlan($planId: ID!, $name: String, $isActive: Boolean) {
  updatePlan(planId: $planId, name: $name, isActive: $isActive) {
    plan {
      ...fragmentPlan
    }
  }
}
