#import "./fragmentImportedOrExportedLivestockManure.gql"

mutation DeleteImportedOrExportedLivestockManure($importedOrExportedLivestockManureId: ID!) {
  deleteImportedOrExportedLivestockManure(importedOrExportedLivestockManureId: $importedOrExportedLivestockManureId) {
    importedOrExportedLivestockManure {
      ...fragmentImportedOrExportedLivestockManure
    }
  }
}
