#import "./fragmentImportedOrExportedLivestockManure.gql"

mutation UpdateImportedOrExportedLivestockManure($importedOrExportedLivestockManureId: ID!, $livestockSpeciesId: ID, $purity: Float, $nitrogenContent: Float, $phosphorusContent: Float, $potassiumContent: Float, $totalQuantity: Float) {
  updateImportedOrExportedLivestockManure(importedOrExportedLivestockManureId: $importedOrExportedLivestockManureId, livestockSpeciesId: $livestockSpeciesId, purity: $purity, nitrogenContent: $nitrogenContent, phosphorusContent: $phosphorusContent, potassiumContent:$potassiumContent, totalQuantity: $totalQuantity) {
    importedOrExportedLivestockManure {
      ...fragmentImportedOrExportedLivestockManure
    }
  }
}
