#import "./fragmentProducedLivestockManure.gql"

mutation DeleteProducedLivestockManure($producedLivestockManureId: ID!) {
  deleteProducedLivestockManure(producedLivestockManureId: $producedLivestockManureId) {
    producedLivestockManure {
      ...fragmentProducedLivestockManure
    }
  }
}
