# Generated by Django 2.1.2 on 2019-01-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmParcelCropNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_yield', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_nitrogen_needed', models.FloatField(blank=True, null=True)),
                ('estimated_phosphorus_needed', models.FloatField(blank=True, null=True)),
                ('estimated_potassium_needed', models.FloatField(blank=True, null=True)),
                ('priority_order', models.IntegerField(blank=True, null=True)),
                ('farm_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_needs', to='farming.FarmParcel')),
            ],
        ),
        migrations.CreateModel(
            name='FarmParcelNutrientPlanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manure_quantity', models.FloatField(default=0)),
                ('chemical_quantity', models.FloatField(default=0)),
                ('chemical_type', models.CharField(blank=True, max_length=25, null=True)),
                ('farm_parcel_crop_needs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_plan_result', to='nmp.FarmParcelCropNeeds')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedOrExportedLivestockManure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purity', models.FloatField()),
                ('nitrogen_content', models.FloatField()),
                ('phosphorus_content', models.FloatField()),
                ('potassium_content', models.FloatField()),
                ('total_quantity', models.FloatField()),
                ('livestock_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_or_exported_livestock_manures', to='farming.LivestockSpecies')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nmp_plans_created', to='core.FaSTUser')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nmp_plans', to='farming.Farm')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nmp_plans_updated', to='core.FaSTUser')),
            ],
        ),
        migrations.CreateModel(
            name='ProducedLivestockManure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purity', models.FloatField()),
                ('nitrogen_content', models.FloatField()),
                ('phosphorus_content', models.FloatField()),
                ('potassium_content', models.FloatField()),
                ('number_of_heads', models.IntegerField()),
                ('storage_days', models.IntegerField()),
                ('liters_per_head_per_day', models.FloatField()),
                ('livestock_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produced_livestock_manures', to='farming.LivestockSpecies')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produced_livestock_manures', to='nmp.Plan')),
            ],
        ),
        migrations.AddField(
            model_name='importedorexportedlivestockmanure',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_or_exported_livestock_manures', to='nmp.Plan'),
        ),
        migrations.AddField(
            model_name='farmparcelcropneeds',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_parcel_crop_needs', to='nmp.Plan'),
        ),
    ]
