# Generated by Django 2.1.5 on 2019-01-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmp', '0003_auto_20190109_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmparcelcropneeds',
            name='priority_order',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmparcelcropneeds',
            name='target_yield',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
