#import "./fragmentFarmParcel.gql"

mutation RemoveFarmParcelFromFarm($farmParcelId: ID!) {
  removeFarmParcelFromFarm(farmParcelId: $farmParcelId) {
    farmParcel {
      ...fragmentFarmParcel
    }
  }
}
