# Generated by Django 2.1.2 on 2019-01-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('additional_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicesubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_subscriptions', to='core.FaSTUser'),
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additional_services.Provider'),
        ),
        migrations.AddField(
            model_name='service',
            name='subscription_type',
            field=models.ForeignKey(default='FREE', on_delete=django.db.models.deletion.CASCADE, to='additional_services.SubscriptionType'),
        ),
        migrations.AddField(
            model_name='provider',
            name='owners',
            field=models.ManyToManyField(to='core.FaSTUser'),
        ),
        migrations.AlterUniqueTogether(
            name='userservicesubscription',
            unique_together={('user', 'service')},
        ),
    ]
